Added Documentation to the repository
Tech-Matrix/Face-Detection pull request #4
Opened 2021-09-17 15:19 UTC by Mohamed-Ayaan358

#### 
fixes #2 

#### Describe the changes you've made
I have added Documentation for this repository. 

#### Describe if there is any unusual behaviour of your code ( Write `NA` if there isn't )
NA

#### Additional context
![image](https://user-images.githubusercontent.com/72858215/133806345-60044754-253d-4678-ab8f-007986bad539.png)

#### Test plan ( Optional but Recommended )
There is no need to test documentation code.

#### Checklist

- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.

2021-09-17 19:30 UTC, A-HK requested changes

2021-09-17 19:30 UTC, A-HK commented on readme.md
> +[![GitHub Pull Requests](https://img.shields.io/github/issues-pr/kylelobo/The-Documentation-Compendium.svg)](https://github.com/Mohamed-Ayaan358/Face-Detection)
I think the link for the `Open Pull Requests` badge should be 
https://github.com/Tech-Matrix/Face-Detection/pulls?q=is%3Aopen+is%3Apr
instead of a link to your fork

2021-09-17 19:30 UTC, A-HK commented on readme.md
> +### Contributors List
Contributors List not necessary in individual projects, sorry for the confusion !

2021-09-17 19:30 UTC, A-HK commented on readme.md
> +  Face detection is an extremely important technology that is used widely around the world and has many uses.
Maybe actually mention a couple of the uses of face detection? (like unlocking phones, forensic investigation)
Just saying `used widely around the world and has many uses` is a little redundant in my opinion.

Instead, maybe say  `used widely around the world, not just for <use-case-1>, but also in <use-case-2>`.
Don't have to stick to this ^ format, just a suggestion!

2021-09-17 19:30 UTC, A-HK commented on readme.md
> +We utilise HaarCascades so as to avoid having to write a seperate object detection algorithm, however their scope is limited due to limited number of haarCascades.
Small typo xD - change `seperate` to `separate`

2021-09-17 19:34 UTC, A-HK commented
Hey @Mohamed-Ayaan358 , really good job with this !
 I just have a few changes I'd like to request from my side.
Also, since there's a separate repo for the contributors list, another one here is unecessary - that's completely on me, my bad for adding that checkbox in the template.

Meanwhile @charvibannur , you're the resident ML expert - what do you think of this documentation? Does it give an overview of the technical aspects of the project?

2021-09-18 06:33 UTC, charvibannur commented
@Mohamed-Ayaan358 Can you also add steps to execute and run the program? as some people might not be familiar with it.
Otherwise, Great job!!

2021-09-18 15:41 UTC, merged

2021-09-18 15:44 UTC, charvibannur commented
Great work!! I've merged it.